// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpxswvfloirespuaxrgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRweHN3dmZsb2lyZXNwdWF4cmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzk3NzIsImV4cCI6MjA2ODkxNTc3Mn0.NEIFFw1Ooc3MlXm8LZygt17LdhX7P5lw3b9-uEMwa2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});